"""Regression REG-20260626-AGENT08 — dependency cryptography 43.0.1 has PYSEC-2026-35.

Auto-generated by the AEGIS triage agent (Subsystem B). Threat: OWASP A06 (Vulnerable &
Outdated Components). FAILS while the vulnerable version is installed; passes after
upgrading to 46.0.6. Locked into the append-only corpus.
"""
from importlib.metadata import version as _installed_version


def test_cryptography_pysec_2026_35_not_vulnerable_version():
    assert _installed_version("cryptography") != "43.0.1", (
        "vulnerable cryptography==43.0.1 still installed; upgrade to 46.0.6"
    )
