"""Regression REG-20260626-AGENT03 — dependency pyjwt 2.9.0 has PYSEC-2026-179.

Auto-generated by the AEGIS triage agent (Subsystem B). Threat: OWASP A06 (Vulnerable &
Outdated Components). FAILS while the vulnerable version is installed; passes after
upgrading to 2.13.0. Locked into the append-only corpus.
"""
from importlib.metadata import version as _installed_version


def test_pyjwt_pysec_2026_179_not_vulnerable_version():
    assert _installed_version("pyjwt") != "2.9.0", (
        "vulnerable pyjwt==2.9.0 still installed; upgrade to 2.13.0"
    )
