"""Regression REG-20260626-AGENT09 — dependency cryptography 43.0.1 has GHSA-79v4-65xg-pq4g.

Auto-generated by the AEGIS triage agent (Subsystem B). Threat: OWASP A06 (Vulnerable &
Outdated Components). FAILS while the vulnerable version is installed; passes after
upgrading to 44.0.1. Locked into the append-only corpus.
"""
from importlib.metadata import version as _installed_version


def test_cryptography_ghsa_79v4_65xg_pq4g_not_vulnerable_version():
    assert _installed_version("cryptography") != "43.0.1", (
        "vulnerable cryptography==43.0.1 still installed; upgrade to 44.0.1"
    )
