"""Regression REG-20260626-AGENT10 — dependency cryptography 43.0.1 has GHSA-r6ph-v2qm-q3c2.

Auto-generated by the AEGIS triage agent (Subsystem B). Threat: OWASP A06 (Vulnerable &
Outdated Components). FAILS while the vulnerable version is installed; passes after
upgrading to 46.0.5. Locked into the append-only corpus.
"""
from importlib.metadata import version as _installed_version


def test_cryptography_ghsa_r6ph_v2qm_q3c2_not_vulnerable_version():
    assert _installed_version("cryptography") != "43.0.1", (
        "vulnerable cryptography==43.0.1 still installed; upgrade to 46.0.5"
    )
