"""Regression REG-20260626-AGENT11 — dependency cryptography 43.0.1 has GHSA-537c-gmf6-5ccf.

Auto-generated by the AEGIS triage agent (Subsystem B). Threat: OWASP A06 (Vulnerable &
Outdated Components). FAILS while the vulnerable version is installed; passes after
upgrading to 48.0.1. Locked into the append-only corpus.
"""
from importlib.metadata import version as _installed_version


def test_cryptography_ghsa_537c_gmf6_5ccf_not_vulnerable_version():
    assert _installed_version("cryptography") != "43.0.1", (
        "vulnerable cryptography==43.0.1 still installed; upgrade to 48.0.1"
    )
